version: "3.8"

services:
  instantsplat:
    image: instantsplat:latest
    build:
      context: ..
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics
      DISPLAY: $DISPLAY
    volumes:
      - ../:/InstantSplat
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /InstantSplat
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

